version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./backend/projdb.sql:/docker-entrypoint-initdb.d/projdb.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=projdb
    restart: always
    networks:
      - testnet
  backend:
    build: ./backend
    ports:
      - 5001:5000
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONPATH=${PYTHONPATH}:/app/backend
    depends_on:
      - postgres
    networks:
      - testnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - testnet

networks:
  testnet: