FROM python:3.8
WORKDIR /app/backend
COPY requirements.txt /app/backend
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app/backend

ENV FLASK_APP=server.py
ENV FLASK_ENV=development
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5001

# Run the application
CMD ["flask", "run"]
